# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b524a63f3557ba6762f67cb9876b0021bc6b2191fa6b9fd8597e2a79a880e372913fa1e0ceb640d3a339202914f5d892f2bbc16df0a7a933e98e0e9e3ca8db9

test:
  secret_key_base: 0846489a4c5fbf670ab8d9f319790f2124220ede7bd54ca2478ceefc98e2033ac3598e8648a3002ca45e92bbb138c9856b5b50be8b2dc2f3b35d774e9a40becc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
